seed_top_k: [128,128]
seed_radius_coe: 0.01
net_channels: 128
layer_num: 9
head: 4
seedlayer: [0,6]
use_mc_seeding: True
use_score_encoding: False
conf_bar: [1,0]
sink_iter: [10,10]
detach_iter: 1000000
domain_topk: 10
domain_radiues: 0.01
separate_num1: 100
separate_num2: 80