seed_top_k: [256,256] #种子数量
seed_radius_coe: 0.01 #NMS半径超参数
net_channels: 128 #网络通道数量
layer_num: 9
head: 4
seedlayer: [0,6]
use_mc_seeding: True
use_score_encoding: False
conf_bar: [1,0.1]
sink_iter: [10,100]
detach_iter: 140000
p_th: 0.2
domain_topk: 10
domain_radiues: 0.01
separate_num1: 200
separate_num2: 128